//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormDemo.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Ekle(WebFormDemo.ServiceReference1.Personel personel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EkleAsync(WebFormDemo.ServiceReference1.Personel personel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetirById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebFormDemo.ServiceReference1.Personel GetirById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetirById", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormDemo.ServiceReference1.Personel> GetirByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Guncelle(WebFormDemo.ServiceReference1.Personel personel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> GuncelleAsync(WebFormDemo.ServiceReference1.Personel personel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Sil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sil", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SilAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetirHepsi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetirHepsi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetirHepsi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetirHepsiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool LoginKontrol(WebFormDemo.ServiceReference1.Kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginKontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> LoginKontrolAsync(WebFormDemo.ServiceReference1.Kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YetkiliMi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool YetkiliMi(WebFormDemo.ServiceReference1.Kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YetkiliMi", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> YetkiliMiAsync(WebFormDemo.ServiceReference1.Kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sha256_hash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sha256_hash(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sha256_hash", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sha256_hashAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Ekle2(WebFormDemo.ServiceReference1.YeniKullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ekle2", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Ekle2Async(WebFormDemo.ServiceReference1.YeniKullanici kullanici);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Personel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string adField;
        
        private string soyadField;
        
        private string maasField;
        
        private string sehirField;
        
        private string meslekField;
        
        private string telNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
                this.RaisePropertyChanged("Ad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Soyad {
            get {
                return this.soyadField;
            }
            set {
                this.soyadField = value;
                this.RaisePropertyChanged("Soyad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Maas {
            get {
                return this.maasField;
            }
            set {
                this.maasField = value;
                this.RaisePropertyChanged("Maas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sehir {
            get {
                return this.sehirField;
            }
            set {
                this.sehirField = value;
                this.RaisePropertyChanged("Sehir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Meslek {
            get {
                return this.meslekField;
            }
            set {
                this.meslekField = value;
                this.RaisePropertyChanged("Meslek");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TelNo {
            get {
                return this.telNoField;
            }
            set {
                this.telNoField = value;
                this.RaisePropertyChanged("TelNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YeniKullanici : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kullaniciAdiField;
        
        private string sifreField;
        
        private bool yetkiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("KullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
                this.RaisePropertyChanged("Sifre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Yetki {
            get {
                return this.yetkiField;
            }
            set {
                this.yetkiField = value;
                this.RaisePropertyChanged("Yetki");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Kullanici : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kullaniciAdiField;
        
        private string sifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("KullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
                this.RaisePropertyChanged("Sifre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WebFormDemo.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WebFormDemo.ServiceReference1.Service1Soap>, WebFormDemo.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public bool Ekle(WebFormDemo.ServiceReference1.Personel personel) {
            return base.Channel.Ekle(personel);
        }
        
        public System.Threading.Tasks.Task<bool> EkleAsync(WebFormDemo.ServiceReference1.Personel personel) {
            return base.Channel.EkleAsync(personel);
        }
        
        public WebFormDemo.ServiceReference1.Personel GetirById(int id) {
            return base.Channel.GetirById(id);
        }
        
        public System.Threading.Tasks.Task<WebFormDemo.ServiceReference1.Personel> GetirByIdAsync(int id) {
            return base.Channel.GetirByIdAsync(id);
        }
        
        public bool Guncelle(WebFormDemo.ServiceReference1.Personel personel) {
            return base.Channel.Guncelle(personel);
        }
        
        public System.Threading.Tasks.Task<bool> GuncelleAsync(WebFormDemo.ServiceReference1.Personel personel) {
            return base.Channel.GuncelleAsync(personel);
        }
        
        public bool Sil(int id) {
            return base.Channel.Sil(id);
        }
        
        public System.Threading.Tasks.Task<bool> SilAsync(int id) {
            return base.Channel.SilAsync(id);
        }
        
        public System.Data.DataTable GetirHepsi() {
            return base.Channel.GetirHepsi();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetirHepsiAsync() {
            return base.Channel.GetirHepsiAsync();
        }
        
        public bool LoginKontrol(WebFormDemo.ServiceReference1.Kullanici kullanici) {
            return base.Channel.LoginKontrol(kullanici);
        }
        
        public System.Threading.Tasks.Task<bool> LoginKontrolAsync(WebFormDemo.ServiceReference1.Kullanici kullanici) {
            return base.Channel.LoginKontrolAsync(kullanici);
        }
        
        public bool YetkiliMi(WebFormDemo.ServiceReference1.Kullanici kullanici) {
            return base.Channel.YetkiliMi(kullanici);
        }
        
        public System.Threading.Tasks.Task<bool> YetkiliMiAsync(WebFormDemo.ServiceReference1.Kullanici kullanici) {
            return base.Channel.YetkiliMiAsync(kullanici);
        }
        
        public string sha256_hash(string value) {
            return base.Channel.sha256_hash(value);
        }
        
        public System.Threading.Tasks.Task<string> sha256_hashAsync(string value) {
            return base.Channel.sha256_hashAsync(value);
        }
        
        public bool Ekle2(WebFormDemo.ServiceReference1.YeniKullanici kullanici) {
            return base.Channel.Ekle2(kullanici);
        }
        
        public System.Threading.Tasks.Task<bool> Ekle2Async(WebFormDemo.ServiceReference1.YeniKullanici kullanici) {
            return base.Channel.Ekle2Async(kullanici);
        }
    }
}
